[2023-08-28T18:42:23.057+0000] {processor.py:157} INFO - Started process (PID=30) to work on /opt/airflow/dags/dag_test.py
[2023-08-28T18:42:23.063+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2023-08-28T18:42:23.086+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:42:23.085+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2023-08-28T18:42:23.205+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:42:23.195+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 16, in <module>
    op1 = SQLExecuteQueryOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 240, in __init__
    super().__init__(conn_id=conn_id, database=database, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 137, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 793, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SQLExecuteQueryOperator (task_id: make_a_staging_table). Invalid arguments were:
**kwargs: {'postgres_conn_id': 'my_pg_connection'}
[2023-08-28T18:42:23.207+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2023-08-28T18:42:23.365+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_test.py took 0.411 seconds
[2023-08-28T18:42:54.141+0000] {processor.py:157} INFO - Started process (PID=88) to work on /opt/airflow/dags/dag_test.py
[2023-08-28T18:42:54.150+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2023-08-28T18:42:54.177+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:42:54.175+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2023-08-28T18:42:54.229+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:42:54.215+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 16, in <module>
    op1 = SQLExecuteQueryOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 240, in __init__
    super().__init__(conn_id=conn_id, database=database, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 137, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 793, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SQLExecuteQueryOperator (task_id: make_a_staging_table). Invalid arguments were:
**kwargs: {'postgres_conn_id': 'my_pg_connection'}
[2023-08-28T18:42:54.236+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2023-08-28T18:42:54.386+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_test.py took 0.281 seconds
[2023-08-28T18:43:24.819+0000] {processor.py:157} INFO - Started process (PID=145) to work on /opt/airflow/dags/dag_test.py
[2023-08-28T18:43:24.822+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2023-08-28T18:43:24.826+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:43:24.826+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2023-08-28T18:43:24.844+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:43:24.838+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 16, in <module>
    op1 = SQLExecuteQueryOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 240, in __init__
    super().__init__(conn_id=conn_id, database=database, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 137, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 793, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SQLExecuteQueryOperator (task_id: make_a_staging_table). Invalid arguments were:
**kwargs: {'postgres_conn_id': 'my_pg_connection'}
[2023-08-28T18:43:24.846+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2023-08-28T18:43:24.877+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_test.py took 0.075 seconds
[2023-08-28T18:43:54.947+0000] {processor.py:157} INFO - Started process (PID=202) to work on /opt/airflow/dags/dag_test.py
[2023-08-28T18:43:54.949+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2023-08-28T18:43:54.962+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:43:54.961+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2023-08-28T18:43:54.987+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:43:54.979+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 16, in <module>
    op1 = SQLExecuteQueryOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 240, in __init__
    super().__init__(conn_id=conn_id, database=database, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 137, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 793, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SQLExecuteQueryOperator (task_id: make_a_staging_table). Invalid arguments were:
**kwargs: {'postgres_conn_id': 'my_pg_connection'}
[2023-08-28T18:43:54.992+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2023-08-28T18:43:55.037+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_test.py took 0.094 seconds
[2023-08-28T18:44:11.419+0000] {processor.py:157} INFO - Started process (PID=234) to work on /opt/airflow/dags/dag_test.py
[2023-08-28T18:44:11.425+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2023-08-28T18:44:11.432+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:44:11.431+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2023-08-28T18:44:11.463+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:44:11.458+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 16, in <module>
    op1 = SQLExecuteQueryOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 240, in __init__
    super().__init__(conn_id=conn_id, database=database, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 137, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 793, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SQLExecuteQueryOperator (task_id: make_a_staging_table). Invalid arguments were:
**kwargs: {'postgres_conn_id': 'postgres_con'}
[2023-08-28T18:44:11.465+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2023-08-28T18:44:11.512+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_test.py took 0.116 seconds
[2023-08-28T18:44:41.911+0000] {processor.py:157} INFO - Started process (PID=291) to work on /opt/airflow/dags/dag_test.py
[2023-08-28T18:44:41.916+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2023-08-28T18:44:41.923+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:44:41.922+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2023-08-28T18:44:42.005+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:44:41.984+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 16, in <module>
    op1 = SQLExecuteQueryOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 240, in __init__
    super().__init__(conn_id=conn_id, database=database, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 137, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 793, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SQLExecuteQueryOperator (task_id: make_a_staging_table). Invalid arguments were:
**kwargs: {'postgres_conn_id': 'postgres_con'}
[2023-08-28T18:44:42.008+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2023-08-28T18:44:42.071+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_test.py took 0.170 seconds
[2023-08-28T18:45:13.020+0000] {processor.py:157} INFO - Started process (PID=348) to work on /opt/airflow/dags/dag_test.py
[2023-08-28T18:45:13.022+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2023-08-28T18:45:13.025+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:45:13.024+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2023-08-28T18:45:13.036+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:45:13.033+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 16, in <module>
    op1 = SQLExecuteQueryOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 240, in __init__
    super().__init__(conn_id=conn_id, database=database, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 137, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 793, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SQLExecuteQueryOperator (task_id: make_a_staging_table). Invalid arguments were:
**kwargs: {'postgres_conn_id': 'postgres_con'}
[2023-08-28T18:45:13.039+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2023-08-28T18:45:13.056+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_test.py took 0.040 seconds
[2023-08-28T18:45:43.932+0000] {processor.py:157} INFO - Started process (PID=404) to work on /opt/airflow/dags/dag_test.py
[2023-08-28T18:45:43.935+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2023-08-28T18:45:43.942+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:45:43.941+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2023-08-28T18:45:43.979+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:45:43.968+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 16, in <module>
    op1 = SQLExecuteQueryOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 240, in __init__
    super().__init__(conn_id=conn_id, database=database, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 137, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 793, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SQLExecuteQueryOperator (task_id: make_a_staging_table). Invalid arguments were:
**kwargs: {'postgres_conn_id': 'postgres_con'}
[2023-08-28T18:45:43.982+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2023-08-28T18:45:44.025+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_test.py took 0.100 seconds
[2023-08-28T18:46:14.741+0000] {processor.py:157} INFO - Started process (PID=461) to work on /opt/airflow/dags/dag_test.py
[2023-08-28T18:46:14.743+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2023-08-28T18:46:14.747+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:46:14.747+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2023-08-28T18:46:14.760+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:46:14.756+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 16, in <module>
    op1 = SQLExecuteQueryOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 240, in __init__
    super().__init__(conn_id=conn_id, database=database, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 137, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 793, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SQLExecuteQueryOperator (task_id: make_a_staging_table). Invalid arguments were:
**kwargs: {'postgres_conn_id': 'postgres_con'}
[2023-08-28T18:46:14.762+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2023-08-28T18:46:14.779+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_test.py took 0.043 seconds
[2023-08-28T18:46:45.282+0000] {processor.py:157} INFO - Started process (PID=518) to work on /opt/airflow/dags/dag_test.py
[2023-08-28T18:46:45.284+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2023-08-28T18:46:45.289+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:46:45.288+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2023-08-28T18:46:45.306+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:46:45.299+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 16, in <module>
    op1 = SQLExecuteQueryOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 240, in __init__
    super().__init__(conn_id=conn_id, database=database, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 137, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 793, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SQLExecuteQueryOperator (task_id: make_a_staging_table). Invalid arguments were:
**kwargs: {'postgres_conn_id': 'postgres_con'}
[2023-08-28T18:46:45.308+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2023-08-28T18:46:45.342+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_test.py took 0.065 seconds
[2023-08-28T18:47:15.458+0000] {processor.py:157} INFO - Started process (PID=575) to work on /opt/airflow/dags/dag_test.py
[2023-08-28T18:47:15.460+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2023-08-28T18:47:15.463+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:47:15.463+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2023-08-28T18:47:15.476+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:47:15.471+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 16, in <module>
    op1 = SQLExecuteQueryOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 240, in __init__
    super().__init__(conn_id=conn_id, database=database, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 137, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 793, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SQLExecuteQueryOperator (task_id: make_a_staging_table). Invalid arguments were:
**kwargs: {'postgres_conn_id': 'postgres_con'}
[2023-08-28T18:47:15.477+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2023-08-28T18:47:15.503+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_test.py took 0.048 seconds
[2023-08-28T18:47:21.183+0000] {processor.py:157} INFO - Started process (PID=587) to work on /opt/airflow/dags/dag_test.py
[2023-08-28T18:47:21.185+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2023-08-28T18:47:21.188+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:47:21.188+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2023-08-28T18:47:21.213+0000] {processor.py:839} INFO - DAG(s) dict_keys(['testing_dag']) retrieved from /opt/airflow/dags/dag_test.py
[2023-08-28T18:47:21.308+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:47:21.308+0000] {manager.py:501} INFO - Created Permission View: can delete on DAG:testing_dag
[2023-08-28T18:47:21.314+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:47:21.314+0000] {manager.py:501} INFO - Created Permission View: can read on DAG:testing_dag
[2023-08-28T18:47:21.319+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:47:21.319+0000] {manager.py:501} INFO - Created Permission View: can edit on DAG:testing_dag
[2023-08-28T18:47:21.338+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:47:21.337+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-08-28T18:47:21.353+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:47:21.352+0000] {dag.py:2929} INFO - Creating ORM DAG for testing_dag
[2023-08-28T18:47:21.355+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:47:21.354+0000] {dag.py:3677} INFO - Setting next_dagrun for testing_dag to None, run_after=None
[2023-08-28T18:47:21.369+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_test.py took 0.191 seconds
[2023-08-28T18:47:51.900+0000] {processor.py:157} INFO - Started process (PID=641) to work on /opt/airflow/dags/dag_test.py
[2023-08-28T18:47:51.903+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2023-08-28T18:47:51.909+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:47:51.909+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2023-08-28T18:47:51.921+0000] {processor.py:839} INFO - DAG(s) dict_keys(['testing_dag']) retrieved from /opt/airflow/dags/dag_test.py
[2023-08-28T18:47:51.943+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:47:51.943+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-08-28T18:47:51.957+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:47:51.957+0000] {dag.py:3677} INFO - Setting next_dagrun for testing_dag to None, run_after=None
[2023-08-28T18:47:51.972+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_test.py took 0.078 seconds
[2023-08-28T18:48:22.259+0000] {processor.py:157} INFO - Started process (PID=699) to work on /opt/airflow/dags/dag_test.py
[2023-08-28T18:48:22.263+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2023-08-28T18:48:22.270+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:48:22.269+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2023-08-28T18:48:22.279+0000] {processor.py:839} INFO - DAG(s) dict_keys(['testing_dag']) retrieved from /opt/airflow/dags/dag_test.py
[2023-08-28T18:48:22.308+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:48:22.308+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-08-28T18:48:22.319+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:48:22.319+0000] {dag.py:3677} INFO - Setting next_dagrun for testing_dag to None, run_after=None
[2023-08-28T18:48:22.335+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_test.py took 0.079 seconds
[2023-08-28T18:48:52.483+0000] {processor.py:157} INFO - Started process (PID=755) to work on /opt/airflow/dags/dag_test.py
[2023-08-28T18:48:52.489+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2023-08-28T18:48:52.497+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:48:52.496+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2023-08-28T18:48:52.515+0000] {processor.py:839} INFO - DAG(s) dict_keys(['testing_dag']) retrieved from /opt/airflow/dags/dag_test.py
[2023-08-28T18:48:52.575+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:48:52.575+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-08-28T18:48:52.591+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:48:52.590+0000] {dag.py:3677} INFO - Setting next_dagrun for testing_dag to None, run_after=None
[2023-08-28T18:48:52.611+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_test.py took 0.146 seconds
[2023-08-28T18:49:22.662+0000] {processor.py:157} INFO - Started process (PID=811) to work on /opt/airflow/dags/dag_test.py
[2023-08-28T18:49:22.664+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2023-08-28T18:49:22.671+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:49:22.671+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2023-08-28T18:49:22.691+0000] {processor.py:839} INFO - DAG(s) dict_keys(['testing_dag']) retrieved from /opt/airflow/dags/dag_test.py
[2023-08-28T18:49:22.714+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:49:22.713+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-08-28T18:49:22.725+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:49:22.725+0000] {dag.py:3677} INFO - Setting next_dagrun for testing_dag to None, run_after=None
[2023-08-28T18:49:22.754+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_test.py took 0.095 seconds
[2023-08-28T18:49:52.877+0000] {processor.py:157} INFO - Started process (PID=867) to work on /opt/airflow/dags/dag_test.py
[2023-08-28T18:49:52.880+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2023-08-28T18:49:52.883+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:49:52.883+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2023-08-28T18:49:52.891+0000] {processor.py:839} INFO - DAG(s) dict_keys(['testing_dag']) retrieved from /opt/airflow/dags/dag_test.py
[2023-08-28T18:49:52.909+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:49:52.908+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-08-28T18:49:52.921+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:49:52.921+0000] {dag.py:3677} INFO - Setting next_dagrun for testing_dag to None, run_after=None
[2023-08-28T18:49:52.934+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_test.py took 0.059 seconds
[2023-08-28T18:50:23.106+0000] {processor.py:157} INFO - Started process (PID=922) to work on /opt/airflow/dags/dag_test.py
[2023-08-28T18:50:23.107+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2023-08-28T18:50:23.110+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:50:23.109+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2023-08-28T18:50:23.118+0000] {processor.py:839} INFO - DAG(s) dict_keys(['testing_dag']) retrieved from /opt/airflow/dags/dag_test.py
[2023-08-28T18:50:23.136+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:50:23.136+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-08-28T18:50:23.147+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:50:23.147+0000] {dag.py:3677} INFO - Setting next_dagrun for testing_dag to None, run_after=None
[2023-08-28T18:50:23.169+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_test.py took 0.066 seconds
[2023-08-28T18:50:53.495+0000] {processor.py:157} INFO - Started process (PID=979) to work on /opt/airflow/dags/dag_test.py
[2023-08-28T18:50:53.497+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2023-08-28T18:50:53.502+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:50:53.501+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2023-08-28T18:50:53.552+0000] {processor.py:839} INFO - DAG(s) dict_keys(['testing_dag']) retrieved from /opt/airflow/dags/dag_test.py
[2023-08-28T18:50:53.570+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:50:53.570+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-08-28T18:50:53.583+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:50:53.583+0000] {dag.py:3677} INFO - Setting next_dagrun for testing_dag to None, run_after=None
[2023-08-28T18:50:53.602+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_test.py took 0.110 seconds
[2023-08-28T18:51:24.004+0000] {processor.py:157} INFO - Started process (PID=1036) to work on /opt/airflow/dags/dag_test.py
[2023-08-28T18:51:24.006+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2023-08-28T18:51:24.016+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:51:24.015+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2023-08-28T18:51:24.035+0000] {processor.py:839} INFO - DAG(s) dict_keys(['testing_dag']) retrieved from /opt/airflow/dags/dag_test.py
[2023-08-28T18:51:24.064+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:51:24.064+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-08-28T18:51:24.073+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:51:24.073+0000] {dag.py:3677} INFO - Setting next_dagrun for testing_dag to None, run_after=None
[2023-08-28T18:51:24.085+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_test.py took 0.085 seconds
[2023-08-28T18:51:54.317+0000] {processor.py:157} INFO - Started process (PID=1090) to work on /opt/airflow/dags/dag_test.py
[2023-08-28T18:51:54.320+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2023-08-28T18:51:54.332+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:51:54.331+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2023-08-28T18:51:54.345+0000] {processor.py:839} INFO - DAG(s) dict_keys(['testing_dag']) retrieved from /opt/airflow/dags/dag_test.py
[2023-08-28T18:51:54.382+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:51:54.382+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-08-28T18:51:54.396+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:51:54.396+0000] {dag.py:3677} INFO - Setting next_dagrun for testing_dag to None, run_after=None
[2023-08-28T18:51:54.411+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_test.py took 0.098 seconds
[2023-08-28T18:52:24.643+0000] {processor.py:157} INFO - Started process (PID=1148) to work on /opt/airflow/dags/dag_test.py
[2023-08-28T18:52:24.648+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2023-08-28T18:52:24.655+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:52:24.654+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2023-08-28T18:52:24.673+0000] {processor.py:839} INFO - DAG(s) dict_keys(['testing_dag']) retrieved from /opt/airflow/dags/dag_test.py
[2023-08-28T18:52:24.720+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:52:24.719+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-08-28T18:52:24.742+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:52:24.742+0000] {dag.py:3677} INFO - Setting next_dagrun for testing_dag to None, run_after=None
[2023-08-28T18:52:24.772+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_test.py took 0.139 seconds
[2023-08-28T18:52:55.607+0000] {processor.py:157} INFO - Started process (PID=1207) to work on /opt/airflow/dags/dag_test.py
[2023-08-28T18:52:55.612+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2023-08-28T18:52:55.620+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:52:55.619+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2023-08-28T18:52:55.654+0000] {processor.py:839} INFO - DAG(s) dict_keys(['testing_dag']) retrieved from /opt/airflow/dags/dag_test.py
[2023-08-28T18:52:55.725+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:52:55.725+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-08-28T18:52:55.763+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:52:55.762+0000] {dag.py:3677} INFO - Setting next_dagrun for testing_dag to None, run_after=None
[2023-08-28T18:52:55.804+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_test.py took 0.216 seconds
[2023-08-28T18:53:26.919+0000] {processor.py:157} INFO - Started process (PID=1265) to work on /opt/airflow/dags/dag_test.py
[2023-08-28T18:53:26.923+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2023-08-28T18:53:26.928+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:53:26.927+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2023-08-28T18:53:26.947+0000] {processor.py:839} INFO - DAG(s) dict_keys(['testing_dag']) retrieved from /opt/airflow/dags/dag_test.py
[2023-08-28T18:53:26.982+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:53:26.982+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-08-28T18:53:26.995+0000] {logging_mixin.py:151} INFO - [2023-08-28T18:53:26.994+0000] {dag.py:3677} INFO - Setting next_dagrun for testing_dag to None, run_after=None
[2023-08-28T18:53:27.014+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_test.py took 0.107 seconds
